### ISSUE TITLE
Readme ?

### ISSUE THREAD

**Issue by lionpeloux** [mitjap/pwmvs#9]
Hello,

I would like to get dense reconstruction inside Colmap, as I am working on macOs and don't have an NVIDIA graphic card with CUDA.

Would you mind sharing few lines in a readme or in this topic on how to install your program ?
Does it require OpenMVG and/or OpenMVS ?
How do I tell Colmap to use PWMS for the dense reconstruction step ?

Many Thanks

**Comment by mitjap** [comment]
Sorry for late reply :D. I just uploaded the README with some instructions on how to build, install and use PWMVS.

This software works with OpenMVG and ETH3D out of the box. I'm not sure if it is possible to export COLMAP project to any other format that would be compatible with PWMVS. You would need to create an interface similar to https://github.com/mitjap/pwmvs/blob/master/include/workspace_io_eth3d.hpp that would read COLMAP project.
